version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./.resources/mysql:/var/lib/mysql
